export const COMMAND_GET_DEVICE_DATA = 0x08
export const COMMAND_GET_FIRMWARE_VERSION = 0x01
export const COMMAND_GET_RADIO_FIRMWARE_VERSION = 0x02
export const COMMAND_GET_BLUETOOTH_FIRMWARE_VERSION = 0x1B
export const COMMAND_GET_RADIO_SETTINGS = 0x09
export const COMMAND_GET_VOLTAGE = 0X1E
export const COMMAND_MAKE_DEPLOY = 0x1F

export const COMMAND_START_FIRWMARE_UPDATE = 0x03
export const COMMAND_START_ROW = 0x04
export const COMMAND_ROW_PIECE = 0x05
export const COMMAND_END_ROW = 0x06
export const COMMAND_FINISH_FIRMWARE_UPDATE = 0x07
