export const COMMAND_GET_DEVICE_DATA = 0x08
export const COMMAND_GET_FIRMWARE_VERSION = 0x01
export const COMMAND_GET_RADIO_FIRMWARE_VERSION = 0x02
export const COMMAND_GET_BLUETOOTH_FIRMWARE_VERSION = 0x1B
export const COMMAND_GET_RADIO_SETTINGS = 0x09
export const COMMAND_GET_VOLTAGE = 0X1E
export const COMMAND_MAKE_DEPLOY = 0x1F
export const COMMAND_FORCE_UNPAIR = [0x20,0x01]


export const COMMAND_START_FIRWMARE_UPDATE = 0x03
export const COMMAND_START_ROW = 0x04
export const COMMAND_ROW_PIECE = 0x05
export const COMMAND_END_ROW = 0x06
export const COMMAND_FINISH_FIRMWARE_UPDATE = 0x07

export const COMMAND_GET_REGISTERED_BOARD_1 = 0x18
export const COMMAND_GET_REGISTERED_BOARD_2 = 0x19

export const COMMAND_GET_APP_PIC_VERSION = 0x33
export const COMMAND_GET_RADIO_PIC_VERSION = 0x34

export const COMMAND_START_MSG_PACKAGE = 0x30
export const COMMAND_PACKAGE_MSG_PIECE = 0x31
export const COMMAND_SEND_MSG_PACKAGE = 0x32


